<?php

define('ID_SET_TYPE_WOMEN_SINGLES', 1);
define('ID_SET_TYPE_MEN_SINGLES', 2);
define('ID_SET_TYPE_MIXED_DOUBLES', 3);
define('ID_SET_TYPE_WOMEN_DOUBLES', 4);
define('ID_SET_TYPE_MEN_DOUBLES', 5);